### ISSUE TITLE
Improvised UX Flow and App Design Enhancement Idea

### ISSUE THREAD

**Issue by rajhraval1** [cambardell/Footnote#24] opened 2020-09-27 11:36 UTC
I had forked a repository and try to run the app and test the features it provides. The app idea is quite good, but the design and user-experience is not so optimal. ie: Customising and sharing the quote, the sheet dismissal etc. 

After viewing all the possibilities of the app, I'd like to offer my contribution in the developing app user interface and the improvising the UX and UI Design of the app. 

As of now I have:
- Created an improvised UX Flow.
- Created improvised app design.

Here is the diagram for the improvised with the explanation:
![Footnote - New UX Flow](https://user-images.githubusercontent.com/35184001/94363230-79bb7480-00de-11eb-822f-dc664029ccc3.png)

Old UX:
A List displays the quotes (footnotes in terms of app nomenclature), when a user clicks then only user can edit, share the quote. Before sharing there is customisation phase (A sheet is used for customisation) , which as of now is bit of bugs, after customisation it proceeds sharing the footnote and this is how the app works.

New UX:
When user adds a footnote, a sheet appears to enter the data ie: Quote, Quote Author, Book Title and if data is incomplete the textfields show warnings. After entering the data, sheet closes and the use can view the footnote in list. The footnote provides three actions: Edit, Share and Delete.

- Edit Action (Opens a Sheet): Edits the data only
- Share Action (Opens an AlertSheet): Provides two options ie: 
  - Customise and share the Footnote (Background and Text Color, Text Font and Aligment) (Opens up a Full Page Sheet)
  - Share Directly (Shares only the text content of the footnote) (Opens up the Activity View for sharing)
- Delete Action (Opens an Alert): Deletes the quote

Goal to improvise the UX is to provide more transparency in actions.

Here are the app design transitions: The Old Design vs The New Design Planned

| Old Design - Home Screen  |  New Design - Home Screen - Iteration A | New Design - Home Screen - Iteration B  |
|---|---|---|
| ![Old Home Screen](https://user-images.githubusercontent.com/35184001/94363674-72e23100-00e1-11eb-8171-2878261d7a00.png) | ![Footnote - Home Screen - Iteration A](https://user-images.githubusercontent.com/35184001/94363692-92795980-00e1-11eb-9491-e5f7757efc85.png) | ![Footnote - Home Screen - Iteration B](https://user-images.githubusercontent.com/35184001/94363695-986f3a80-00e1-11eb-9b11-c20b9f3aaae9.png)|

| Old Design - Add Quote | New Design - Add Quote | New Design - Add Quote (Warning State)|
|---|---|---|
| ![Add Quote Old](https://user-images.githubusercontent.com/35184001/94363739-087dc080-00e2-11eb-8797-745fbd805dba.png) | ![Footnote - Add Quote View - Without Warnings](https://user-images.githubusercontent.com/35184001/94363746-1c292700-00e2-11eb-9dc7-bf6867d9d610.png) | ![Footnote - Add Quote View - With Warnings](https://user-images.githubusercontent.com/35184001/94363752-23e8cb80-00e2-11eb-92cc-4ed73d0b1ab8.png) |

| Old Design - Customising Quote | New Design - Customising Quote |
|---|---|
| ![image](https://user-images.githubusercontent.com/35184001/94363821-85a93580-00e2-11eb-9e6d-dbe8c82891ac.png)| ![Footnote - Customise and Share](https://user-images.githubusercontent.com/35184001/94363831-978ad880-00e2-11eb-8ee0-d1abbc3b6a98.png)|
*I have removed the background image and font size option* 

| Share Action - OnClick | Delete Action - OnClick|
|---|---|
| ![Footnote - Share Quote - Iteration A](https://user-images.githubusercontent.com/35184001/94363873-e59fdc00-00e2-11eb-960f-3efb1aac6cf8.png) | ![Footnote - Delete Quote - Iteration A](https://user-images.githubusercontent.com/35184001/94363878-f5b7bb80-00e2-11eb-953b-58d8ad7657fe.png)|

In further stages, I tend to work and design:
- Customised Navigation Bar
- Widgets

I would love to code and implement these changes. 
Waiting for the review and opinions.

**Comment by cambardell** [comment] 2020-09-27 19:05
Thanks @rajhraval1! There's a lot of great ideas here. I think it would be better to split off into multiple issues, rather than tackle them all at once. That way some of it can be assigned to other people as well. Here's what I'm thinking, in no particular order: 

1. There's already an issue open for saving empty items: #21 
2. Defaulting to the add quote screen when list is empty could create a confusing onboarding experience, but the app does need some sort of indication of what to do the first time it is opened. An issue could be created for this. 
3. There is an issue open for adding new features to the customization screen (#19), but there should be a separate issue for replacing custom controls with default controls. These are left over from SwiftUI 1.0, when there were issues with default controls.
4. The card design is nice, but limits information density. In your example, only two quotes are visible on screen at once. The current design places emphasis on the text, which I think is the correct choice for this app. 
5. Another advantage of lists vs cards is that we can take advantage of the default "swipe to delete" functionality. This reduces the need for an alert dialogue upon deletion, since this is expected behaviour. 

Thanks again for your work, you made a lot of good points that I will refer people to. To summarize, I'll close this issue and create a couple new ones with the ideas presented here, just to limit the scope of each issue and leave an opportunity for more people to contribute. Some of these ideas are beyond the scope of Hacktoberfest since they would require a more fundamental rewrite, but will be kept here as a reference for a future version 2.0.

**Comment by cambardell** [comment] 2020-09-27 19:09
Closed for scope. Several ideas moved to separate issues, several saved for a future version of the app. Larger explanation above.

**Closed** 2020-09-27 19:09 UTC
Labels: enhancement
